import { createElement } from 'lwc';
import ContactTable from 'c/contactTable';

describe('c-contact-table', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-contact-table', {
            is: ContactTable
        });
        document.body.appendChild(element);
        expect(1).toBe(2);
    });
});